# Generated by Django 5.1.4 on 2024-12-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_planoadquirido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
